# Generated by Django 4.2.6 on 2023-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
