# Generated by Django 4.2.4 on 2023-08-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgory',
            new_name='Category',
        ),
    ]
